### ISSUE TITLE
sf/condo affordablity

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/DMPED#11]
after issue - #10 
- [x]  figure out the affordabilty of these units - need to adapt code -from https://github.com/NeighborhoodInfoDC/Equity/blob/master/Prog/Sales_affordability.sas - will need to add more years to the calculation.

**Comment by lhendey** [comment]
@maggiesu0725 - the fhfa website is mentioned in the program that i gave an example of. https://www.fhfa.gov/DataTools/Downloads/Documents/Historical-Summary-Tables/Table15_2016_by_State_and_Year.xls - This is most current file. 

I realized the macro Peter wrote solves for price (which we have) and not income so won't help here. 
( D:\DCDATA\Libraries\Realprop\Macros\max_afford_price.sas)

You could do a macro loop to loop through the years to simplify the code from the example program.

**Comment by maggiesu0725** [comment]
@lhendey  thanks, do we want years prior to 2010?

**Comment by lhendey** [comment]
Yes

Sent from my iPhone

On Jul 2, 2018, at 7:36 PM, Yipeng Su <notifications@github.com<mailto:notifications@github.com>> wrote:


@lhendey<https://github.com/lhendey> thanks, do we want years prior to 2010?

**Comment by lhendey** [comment]
@maggiesu0725 - i'm going to close #10 and batch submit the file you need to work from. I'll tag you when it's on L.

**Comment by lhendey** [comment]
@maggiesu0725 - it looks like you didn't yet pull a branch for this issue? (that's good). I've merged in #10 to the master so if you pull that down you should have access to the data on L and the recent program.

The dataset is dmped.Sales_who_owns_SF_Condo 
There is a flag for 3+ bedrooms: LargeUnit

**Comment by lhendey** [comment]
@maggiesu0725  nevermind, i see there was a branch 11. i merged the master into it.

**Comment by lhendey** [comment]
@maggiesu0725 - could you populate this table? https://urbanorg.app.box.com/file/302739495819

**Comment by lhendey** [comment]
@maggiesu0725 = dmped requested that we run 30% of AMI as well . can you add that to the code, output and table?
