### ISSUE TITLE
Produce table on LIHTC, IZ by bedroom size by Ward

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/DMPED#13]
@mcohenui could you do a table with count of LIHTC units, IZ units by bedroom size and for city ward? 

see for example the ones we're doing with the ACS.  https://urbanorg.app.box.com/file/296223535486  - do you have multiple time periods for LIHTC?

**Comment by mcohenui** [comment]
@lhendey Sure. The LIHTC data set has allocation years back to, I think, 2002.

**Comment by lhendey** [comment]
@mcohenui - do you think i can get this table by tomorrow?

**Comment by mcohenui** [comment]
@lhendey Yes, I think so. I will work on the IZ files today.

**Comment by mcohenui** [comment]
@lhendey How far along the construction process do you want to count IZ units? Only completed? Completed and Under Construction? Or all including planned units that haven't started construction yet?

**Comment by ptatian** [comment]
@mcohenui Just checking in. Is this issue completed? Anymore work to do? Thanks.
