### ISSUE TITLE
Table 1A: Update rent levels sheet to include no cash rent. 

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/DMPED#38]

**Comment by lhendey** [comment]
@rpitingolo - if you are still editing this one - can you go ahead and add a parallel set of rent level indicators for 0 to 2 bedrooms?

**Comment by rpitingolo** [comment]
@lhendey do you want "zero to two" bedrooms? Or zero, 1, and 2 bedrooms?

**Comment by lhendey** [comment]
@rpitingolo "zero to two" bedrooms?

**Comment by lhendey** [comment]
@rpitingolo that was a statement

**Comment by rpitingolo** [comment]
@lhendey ok, i just added the rows to 1a on box if you want to double check there.

**Comment by lhendey** [comment]
@rpitingolo yes looks good.

**Comment by rpitingolo** [comment]
@lhendey ok I'm finishing the code now.
