### ISSUE TITLE
Populate Table 1A

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/DMPED#4]
@Woliver01 to complete this task you will be working with the following files in SAS:

- ncdb.Ncdb_sum_wd12
- ncdb.Ncdb_sum_2010_wd12
- Acs.Acs_2006_10_dc_sum_tr_wd12
- Acs.Acs_2012_16_dc_sum_tr_wd12

and 

- ncdb.Ncdb_sum_city
- ncdb.Ncdb_sum_2010_city
- Acs.Acs_2006_10_dc_sum_tr_city
- Acs.Acs_2012_16_dc_sum_tr_city 

Using  the template found here: https://urbanorg.app.box.com/file/296223535486 your first step is to identify the variable names in the datasets that correspond with the rows in the template. Once you've done that, for most of the cells, it's a matter of transposing the data so that it fits the template. I can help you with that.

In a few cases you will need to calculate change variables by merging the datasets together in SAS and then calculating the change. Then doing a final transpose. That is a little extra work but not especially difficult.

**Comment by lhendey** [comment]
@rpitingolo - NCDB_SUM_2010_wd12 doesn't have any of the vars we need (none are in Census file SF1).  will is going to need to pull the tract vars and a create summaries from file:///L:/Metadata/meta_ncdb_ncdb_master_update.html  as i noted in the analysis plan. Did you go over that with him in person?

**Comment by rpitingolo** [comment]
@lhendey Yes, sorry. I knew and will edit the instructions.
We are meeting in a few minutes. I will review this step with Wil then as well.

**Comment by rpitingolo** [comment]
@lhendey Wil pointed out that Ncdb_master_update apparently does not have bedrooms by owner-occupied units. It seems like a workaround would be to use a formula: OwnerOccupiedUnits = TotalOccupiedUnits - RenterOccupiedUnits for each bedroom size? Does that seem right? 

@Woliver01

**Comment by lhendey** [comment]
@rpitingolo @Woliver01 sounds right.

**Comment by rpitingolo** [comment]
@lhendey can you look at %ACS_summary_geo_source_tr_vars and confirm that we coded the nonfamily vars incorrectly? It looks like B11016 has 16 cells and we skipped over the 1-person non-family.

**Comment by lhendey** [comment]
@rpitingolo - yes it looks incorrect. please fix.
