### ISSUE TITLE
create neighborhood characteristics table based on sf/condo affordability

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/DMPED#45]
@maggiesu0725  - could you create a table like you did in 1D but we want to characterize tracts by their affordability level based on the affordability of single-family homes/condos. 

you could tack this on to the end of the affordability_sf_condo.sas program. you'll need to first sum to the tract level and then  run a proc univariate for PctAffordFirst_80AMI .  go ahead and program it using the 75th percentile of that value as the "concentrated neighborhoods".  Make sense?

**Comment by maggiesu0725** [comment]
@lhendey which years should the concentrate calculation based on?

**Comment by lhendey** [comment]
2017
Sent from my iPhone

On Jul 22, 2018, at 10:37 PM, Yipeng Su <notifications@github.com<mailto:notifications@github.com>> wrote:


@lhendey<https://github.com/lhendey> which years should the concentrate calculation based on?
