### ISSUE TITLE
add 2000 household size to table 1a

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/DMPED#49]
@rpitingolo - can you read in this SF3 2000 tract file -  and convert from 2000 tracts to Ward2012? .  I'd like to be able to figure out the change in the number of households and change in large households.  (fine to do that part in excel if you can output the numbers for household size by number of people. ) 

L:\Libraries\DMPED\Raw\DEC_00_SF3_H016_with_ann.csv  there is a metadata file in there too.

**Comment by rpitingolo** [comment]
@lhendey OK. I can do this.
