### ISSUE TITLE
Rerun Census and ACS microdata tables by ward

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/DMPED#53]
@rpitingolo I've created weight files for the microdata to all us to run approximate summaries of these data by ward. **Please use these weights to create new versions of the large unit study tables by ward.** Instructions are below. 

The weight files are **dmped.weights_puma00_ward12** and **dmped.weights_puma12_ward12**. The weights were created by using a 2010 block to PUMA crosswalk, to which ward (2012) was added, with 2010 housing unit counts. I then used 2012-16 block group data to apportion the block-level housing units by bedroom size. These data were then summarized to determine the proportion of housing units, by bedroom size, in each PUMA that fell within different wards. The resulting adjustment factor (_adjwt_) can be used to reweight the micro data to get ward summaries. 

To use the files, once you've assembled your microdata, you just need to run it through a Proc SQL to add the new weights. 

```
proc format;
  value bedrooms_to_brsize
    0 = "N/A"
    1 = "No bedroom"
    2 = "1 bedroom"
    3 = "2 bedrooms"
    4 = "3 bedrooms"
    5 = "4 bedrooms"
    6-high = "5 or more bedrooms";
run;

proc sql noprint;
  create table ACS_micro_ward as
  select Dat.*, Wt.BrSize, Wt.Puma, Wt.Ward2012, Wt.adjwt, perwt * adjwt as wperwt, hhwt * adjwt as whhwt from 
  ACS_micro as Dat
  full join
  DMPED.Weights_Puma12_ward12 as Wt
  on Dat.puma = Wt.puma and put( Dat.bedrooms, bedrooms_to_brsize. ) = Wt.BrSize
  order by serial, pernum;
quit;
```

Substitute **ACS_micro** with the data set with your microdata. The above example is for the 2012-16 data. To reweight 2000 data, substitute the weight file in the Proc SQL with **DMPED.Weights_Puma00_ward12**.

The Proc Format is necessary for the code to work. 

The above will add the _Ward2012_ variable, as well as two new weight variables, _wperwt_ and _whhwt_, to the microdata. You can then do whatever summary tabulations you need but just substitute the new weight variables for the original versions. Note that these new weights work regardless of whether you are summarizing by ward, puma, or all DC, so I would just make the substitution throughout. 

Note that this process creates additional observations in the microdata, duplicating obs for PUMAs that that intersect more than one ward and, therefore, will affect the calculation of standard errors. I'm not quite sure what the correct way to determine standard errors might be for the ward data, to be honest. 

A couple of issues with the 2000 PUMA weights. MABLE doesn't seem to support 2000 blocks, so I'm basing the weights on 2010 housing unit counts. Furthermore, we don't have a crosswalk for 2010 blocks to 2000 block groups, so I also had to use the 2012-16 bedroom size distribution within blocks for 2000 as well. It would have been better to have used 2000 data for both of those adjustments. This does not affect the PUMA and DC-level bedroom size distributions, but it will affect the ward results.  

Thanks, Rob. Please let me know if you have any questions. cc: @lhendey @maggiesu0725

**Comment by rpitingolo** [comment]
@ptatian thanks for doing this. I think I understand everything but have a question about the duplicating obs. Since the file will now have more obs than the original, it sounds like perwt and hhwt will no longer properly work? And wperwt and whhwt should be used for all weighting, including to PUMA?

**Comment by ptatian** [comment]
@rpitingolo Yes, sorry. I wasn't quite clear about that. For the file that comes out of the SQL, you should not use perwt and hhwt. You should only use wperwt and whhwt. What I meant was, for PUMA and DC level, you will get the same result doing that as you would using perwt and hhwt in the original data set.

**Comment by rpitingolo** [comment]
@ptatian got it. Thank you.

**Comment by ptatian** [comment]
@rpitingolo One more thing I forgot to mention. Since it's done by bedroom size, this reweighting assumes you are excluding all persons in group quarters. In other words, wperwt and whhwt only have values for people in households. If that's a problem, you can always assign the weights for group quarters people to the values of perwt and hhwt.

**Comment by rpitingolo** [comment]
@ptatian that's not a problem. We were excluding group quarters before too.

**Comment by ptatian** [comment]
@rpitingolo When you are able, please give me an ETA on rerunning the tables. Thanks.

**Comment by rpitingolo** [comment]
@ptatian I'm working on this issue today.
