### ISSUE TITLE
Additional report tables

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/DMPED#54]
Working on additional draft report tables, as needed.

**Comment by ptatian** [comment]
- [ ] Change in HHs by size and ward, 2000 to 2012-16

**Comment by lhendey** [comment]
@ptatian  - program is here: L:\Libraries\DMPED\Prog\LgUnit - Add 2000 HH Size to Table 1A.sas

**Comment by lhendey** [comment]
@ptatian - need to fix cost burden in IPUMS tables  - i'll just do that on this issue.

**Comment by ptatian** [comment]
Thanks.

**Comment by ptatian** [comment]
@lhendey @rpitingolo In **Prog\Large unit owner type table 1C.sas**, we are merging the property data with the MAR x-walk and then the address points file. There is a many-to-many relationship between SSLs and addresses, so I'm concerned this process may be duplicating properties in the resulting data. We should check that.

**Comment by lhendey** [comment]
@ptatian  - it was picking up 5 extra observations. I inserted a nodupkey so no extra get added. I'll update the table. @rpitingolo

**Comment by ptatian** [comment]
@lhendey Thanks for checking that. I'm glad it wasn't a big issue.
