### ISSUE TITLE
Populate Table 1B

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/DMPED#8]
@maggiesu0725 the goal is to populate  this  table: 
https://urbanorg.app.box.com/file/299742837701

To do this you can use the most recent ACS data (acs_2012_16_dc_sum_tr_tr10). The analysis plan says to define whether a tract has a concentration of affordable units (you can use 50% for now and we can adjust later if needed). The other thing you need is the crime summary file but you can merge that on by census tract easily.

**Comment by lhendey** [comment]
@maggiesu0725 i added a more detailed set of indicators and tables for Table 1B.  please review the box file. https://urbanorg.app.box.com/file/299742837701  - note i'm looking for the average tract characteristics vs. the % for the whole group. 

Worksheets vary by affordability threshold and concentration of units. 
Aff <1000 median = Tract % of 3+ br units renting under $1000 is above the median ( > 24.8%)
Aff <1000 75th pct = Tract % of 3+ br units renting under $1000 is above the 75th percentile ( > 40.9%)
Aff <1500 median = Tract % of 3+ br units renting under $1500 is above the median ( > 41.8%)
Aff <1500 75th pct = Tract % of 3+ br units renting under $1500 is above the 75th percentile ( > 67.5%)

Let me know if you want to talk through. 

the rows highlighted in yellow will need other programming to produce those tables. please proceed on the non-yellow rows for now. 

cc @rpitingolo

**Comment by maggiesu0725** [comment]
@lhendey what's the difference between these two: NumOwnOHU1det_&years. NumOwnOHU1att&years. ? is the meta data updated so I can check the label for these variables?

**Comment by lhendey** [comment]
@maggiesu0725  no metadata not updated but you can run a proc contents. 1det is 1 unit detached and 1att is 1 unit attached. you can use the var NumOwnOHU1u_&years.  which i created to combine them.

**Comment by lhendey** [comment]
@maggiesu0725  - i should have caught this before - we generally present crime rates as # of crimes per 1000 population. can you correct?
